---
title: "Interactive Maps"
author: "Jackson Dial"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(USAboundaries)
library(leaflet)
library(fs)
library(downloader)
library(sf)
```

```{r load_data}
states <- us_states() %>% 
  filter(!state_name %in% c("Hawaii", "Alaska", "Puerto Rico"))

cities <- us_cities()

us_cities <- cities %>% 
  filter(!state_name %in% c("Hawaii", "Alaska", "Puerto Rico"))

us_big_2 <- us_cities %>% 
  group_by(state_name) %>% 
  arrange(desc(population)) %>% 
  top_n(2, population)

top_cities <- us_big_2 %>% 
  top_n(1, population)
top_cities2 <- us_big_2 %>% 
  top_n(-1, population)


us_3rd_big <- us_cities %>% 
  group_by(state_name) %>% 
  arrange(desc(population)) %>% 
  top_n(3, population)
top_cities3 <- us_3rd_big %>% 
  top_n(-2, population)

id_counties <- us_counties() %>% 
  filter(state_name == "Idaho")

```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!

```

## Data Visualization

```{r plot_data}
leaflet() %>% addTiles() %>% 
  addPolygons(data = states, fill = FALSE, weight = 1, color = "black") %>% 
  addPolygons(data = id_counties, fill = FALSE, weight = 1, color = "blue") %>% 
  addMarkers(data = top_cities, popup = top_cities$population, label = ~paste(city, top_cities$population, sep = "=")) %>% 
  addMarkers(data = top_cities3, popup = top_cities3$population, label = ~paste(city, top_cities3$population, sep = "="))



```

## Conclusions
